services:
  haproxy:
    build: ./haproxy
    ports:
      - "${SERVER1_PORT}:443"
      - "8404:8404"
    volumes:
      - ./certs:/usr/local/etc/haproxy/certs:ro
    depends_on:
      - webserver1
      - webserver2
    networks:
      - app-network
    restart: unless-stopped

  webserver1:
    build: ./webserver1
    environment:
      - SERVER2_PORT=8001
      - CERT_DIR=/app/certs
    volumes:
      - ./certs:/app/certs:ro
    ports:
      - "8001:8001"
    networks:
      - app-network

  webserver2:
    build: ./webserver2
    environment:
      - SERVER3_PORT=8002
      - CERT_DIR=/app/certs
    volumes:
      - ./certs:/app/certs:ro
    ports:
      - "8002:8002"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge